Repository alpaka-group/alpaka3, pull requests merged in 2025-04, with the labels that each got.

#106 refactor accelerator index query operations
  example/tutorial/src/06_cudaLikeKernel.cpp
  include/alpaka/alpaka.hpp
  include/alpaka/mem/FlatIdxContainer.hpp
  include/alpaka/mem/Iter.hpp
  include/alpaka/mem/ThreadSpace.hpp
  include/alpaka/mem/TiledIdxContainer.hpp
  include/alpaka/onAcc.hpp
  include/alpaka/onAcc/Acc.hpp
  include/alpaka/onAcc/WorkGroup.hpp
  include/alpaka/onAcc/internal.hpp
  include/alpaka/onAcc/tag.hpp
  include/alpaka/onAcc/traverse.hpp
  tests/unit/cvecKernelCall/cvecKernelCall.cpp
Labels: refactoring

#105 add more math functions
  include/alpaka/api/unifiedCudaHip/math.hpp
  include/alpaka/math.hpp
  include/alpaka/math/math.hpp
  tests/unit/math/mathFunctions.cpp
Labels: feature

#108 fix trait `GetDynSharedMemBytes`
  include/alpaka/onHost/trait.hpp
Labels: bug

#110 fix `DataPitches` specialization
  include/alpaka/mem/DataPitches.hpp
Labels: bug
