Repository alpaka-group/alpaka3, pull requests merged in 2025-09, with the labels that each got.

#248 refactor code structure
  README.md
  include/alpaka/alpaka.hpp
  include/alpaka/api/cuda/Platform.hpp
  include/alpaka/api/generic.hpp
  include/alpaka/api/hip/Platform.hpp
  include/alpaka/api/host/Device.hpp
  include/alpaka/api/host/Event.hpp
  include/alpaka/api/host/Platform.hpp
  include/alpaka/api/host/Queue.hpp
  include/alpaka/api/host/atomic.hpp
  include/alpaka/api/oneApi/Platform.hpp
  include/alpaka/api/oneApi/Queue.hpp
  include/alpaka/api/syclGeneric/Event.hpp
  include/alpaka/api/syclGeneric/Platform.hpp
  include/alpaka/api/syclGeneric/Queue.hpp
  include/alpaka/api/syclGeneric/atomic.hpp
  include/alpaka/api/unifiedCudaHip/ComputeApi.hpp
  include/alpaka/api/unifiedCudaHip/Event.hpp
  include/alpaka/api/unifiedCudaHip/Platform.hpp
  include/alpaka/api/unifiedCudaHip/Queue.hpp
  include/alpaka/api/unifiedCudaHip/atomic.hpp
  include/alpaka/concepts.hpp
  include/alpaka/interface.hpp
  include/alpaka/internal/interface.hpp
  include/alpaka/mem/MdSpan.hpp
  include/alpaka/mem/View.hpp
  include/alpaka/onAcc/Acc.hpp
  include/alpaka/onAcc/WorkGroup.hpp
  include/alpaka/onAcc/atomic.hpp
  include/alpaka/onAcc/interface.hpp
  include/alpaka/onAcc/internal/SimdConcurrent.hpp
  include/alpaka/onAcc/internal/SimdTransformReduce.hpp
  include/alpaka/onAcc/internal/interface.hpp
  include/alpaka/onHost/Device.hpp
  include/alpaka/onHost/Event.hpp
  include/alpaka/onHost/Queue.hpp
  include/alpaka/onHost/algo/internal/concurrent.hpp
  include/alpaka/onHost/algo/internal/iota.hpp
  include/alpaka/onHost/algo/internal/transform.hpp
  include/alpaka/onHost/algo/internal/transformReduce.hpp
  include/alpaka/onHost/concepts.hpp
  include/alpaka/onHost/interface.hpp
  include/alpaka/onHost/internal/interface.hpp
  include/alpaka/onHost/mem/ManagedView.hpp
  include/alpaka/onHost/mem/stdContainer.hpp
Labels: refactoring

#221 Add alpaka::wait(device) synchronization helper and tests
  include/alpaka/api/host/Device.hpp
  include/alpaka/api/syclGeneric/Device.hpp
  include/alpaka/api/unifiedCudaHip/Device.hpp
  tests/unit/wait/waitDevice.cpp
Labels: feature

#254 fix docs
  docs/source/basic/example.rst
Labels: bug, documentation

#256 Fix FlatIndexContainer for non-divisible stride
  include/alpaka/mem/FlatIdxContainer.hpp
Labels: bug

#263 refactor alpaka's sycl platform implementation
  include/alpaka/api/syclGeneric/Platform.hpp
Labels: refactoring

#264 Sycl: refactor `allocAsync()`
  include/alpaka/api/syclGeneric/Queue.hpp
Labels: refactoring

#271 fix tsan warning
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/finalize.cmake
  include/alpaka/api/host/Queue.hpp
  sanitizers/tsan_suppressions.txt
Labels: bug

#280 fix kernel call without arguments
  include/alpaka/KernelBundle.hpp
  tests/unit/queue/queue.cpp
Labels: bug

#281 describe CMake option `alpaka_EXEC_*` better
  CMakeLists.txt
Labels: documentation

#283 OneApi: fix blocking queue
  include/alpaka/api/oneApi/Queue.hpp
Labels: bug

#284 implement host->host memcpy for all devices
  include/alpaka/api/unifiedCudaHip/MemcpyKind.hpp
  include/alpaka/core/ApiCudaRt.hpp
  include/alpaka/core/ApiHipRt.hpp
  tests/unit/mem/memcpy.cpp
Labels: feature, tests

#285 Ci: add Rocm 7.0
  .github/workflows/ci.yml
  CMakeLists.txt
Labels: CI

#287 fix CMake `alpaka_finalize()`
  cmake/finalize.cmake
Labels: bug

#295 fix some format issues in Sphinx Doc documentation
  docs/source/basic/cheatsheet.rst
  docs/source/dev/logging.rst
Labels: bug, documentation
