Repository alpaka-group/alpaka3, pull requests merged in 2025-08, with the labels that each got.

#194 CI: update compilers
  .github/workflows/ci.yml
  example/scan/CMakeLists.txt
Labels: CI

#201 fix `config.hpp`
  include/alpaka/core/config.hpp
Labels: bug

#205 add alpaka_cxx_std to cmake cache
  CMakeLists.txt
Labels: bug

#202 Use remove_cv before freeing to allow pointers to volatile memory
  include/alpaka/api/syclGeneric/Device.hpp
  include/alpaka/api/syclGeneric/Queue.hpp
  include/alpaka/api/unifiedCudaHip/Device.hpp
  include/alpaka/api/unifiedCudaHip/Queue.hpp
  include/alpaka/core/alignedAlloc.hpp
Labels: bug

#208 remove unused inlcudes and fix warning
  include/alpaka/api/host/Api.hpp
  include/alpaka/api/host/Device.hpp
  include/alpaka/api/host/cpuArchSize.hpp
  include/alpaka/api/host/exec/Serial.hpp
  include/alpaka/api/host/executor.hpp
  include/alpaka/onAcc/internal/SimdTransformReduce.hpp
Labels: refactoring

#209 fix zero byte allocation
  include/alpaka/api/unifiedCudaHip/Device.hpp
  tests/unit/mem/alloc.cpp
Labels: bug

#213 revert riscv simd width if no vector extension is available
  include/alpaka/api/host/cpuArchSize.hpp
Labels: refactoring

#225 fix `core/config.hpp` version macros
  include/alpaka/core/config.hpp
  tests/unit/core/config.cpp
Labels: bug

#234 CI: add nvcc 13.0 and clang 21
  .github/workflows/ci.yml
  CMakeLists.txt
Labels: CI

#243 validate cheat-sheet code snippets
  docs/snippets/cheatsheet.cpp
  docs/source/basic/cheatsheet.rst
  docs/source/conf.py
Labels: documentation, refactoring
